# Generated by Django 5.2.10 on 2026-02-05 15:43

import photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='media', validators=[photos.validators.FileSizeValidator(5)]),
        ),
    ]
